name: Daily Job Fetcher

on:
  schedule:
    - cron: "30 3 * * *" # 3:30 AM UTC = 9:00 AM IST
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    timeout-minutes: 30 # kill after 30 mins
    steps:
      - name: Some step
        timeout-minutes: 10
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev libnss3 libatk-bridge2.0-0 \
            libdrm2 libxkbcommon0 libglib2.0-0 \
            libasound2t64 libxcomposite1 libxdamage1 \
            libxfixes3 libxrandr2 libpango-1.0-0

      - name: Run fetcher
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: node index.js
